### PR TITLE
Update resources.php

### PR DESCRIPTION
**Pull request by lkfitz**
Hey, Linked Research! Writing to share TagTeam (https://tagteam.harvard.edu/) from the Berkman Klein Center for Internet & Society with the Resources list. Let me know if you have any questions or would like any changes. Thank you!

Best,
Kelly

### CODE REVIEW

**Comment by lkfitz** [comment]
No worries! The platform [https://tagteam.harvard.edu/] is an open source tagging and aggregation platform that enables folks to tag online resources and develop folksonomies and controlled vocabularies for their content. Here's an example of a vocabulary as it exists in one project: https://tagteam.harvard.edu/hubs/oatp/tags. Right now, the Harvard University hosted instance of TagTeam is geared toward research projects. Let me know if you have any questions - thanks!

- Kelly

**Comment by csarven** [comment]
Thanks Kelly. I'm still not seeing an RDF-based description of the terms. What am I missing?

While acknowledging that it is folksonomy driven, this project could fit under "Reviews and Annotations" if it is (or becomes) Linked Data based. What do you think?

**Comment by lkfitz** [comment]
Afternoon, Sarven,
No worries - right now, vocabularies and their associated feeds aren't available in RDF (if they are, I'm out of the loop), but are in RSS/Atom/JSON. 

If the scope of the vocabularies and ontologies section is geared toward tools for creating vocabularies, I feel like TagTeam would be a good fit here - that said, if the scope of the section is dedicated to vocabularies and ontologies themselves, it may be a better fit in sections for Reviews and Annotations or Collaboration. Let me know what you think would be the best fit.

Best,
Kelly

**Comment by lkfitz** [comment]
Afternoon, Sarven,
Let me know if you have any feedback or suggestions - thank you!

Best,
Kelly

**Comment by lkfitz** [comment]
Afternoon - Let me know if you have any questions on this - thanks!

- Kelly

**Comment by csarven** [comment]
Please pardon my poor administration as I've overlooked this issue. /resources is removed from the website altogether so unfortunately we can't include this PR.

**Pull request closed without merging**
